import type { Mua } from "@/lib/types";
import type { AdminMuaSegment } from "@/lib/admin-muas-query";
import type { AdminPlanTag } from "@/lib/admin-plan-tag";

export type AdminMuaListItem = Mua & {
  weeklyCap: number;
  baseWeeklyCap: number;
  weeklyCapOverride: number | null;
  weeklyCapBonus: number;
  weeklyUsed: number;
  totalBookingRevenue: number;
  totalBookings: number;
  totalPushes: number;
  bookingsSincePlanStart: number;
  pushesSincePlanStart: number;
  assuredBookings: number | null;
  monthlyPushTarget: number | null;
  hasPlanHistory: boolean;
  segment: AdminMuaSegment;
  salesRmName: string | null;
  assignedRmName: string | null;
  planRmName: string | null;
  salesPipelineId: string | null;
  salesRmId: string | null;
  salesPipelineStage: string | null;
  salesPipelineMuaType: string | null;
  daysUnassigned: number | null;
  daysSinceStageUpdate: number | null;
  hasActiveSalesPipeline: boolean;
  hasRejectedSalesPipeline: boolean;
  rejectedPipelineId: string | null;
  rejectionReason: string | null;
  rejectionNote: string | null;
  adminPlanTag: AdminPlanTag | null;
  leadCap: number | null;
  leadBudget: string | null;
  planStates: string[];
  planCities: string[];
};
