import fs from "node:fs";
import path from "node:path";
import {
  PLANS_PRICING_DOC,
  RAG_DIR,
  SALES_AI_DOCS,
  SUPPORT_POLICY_DOCS,
  normalizeRagContent,
  readRagFile,
} from "@/lib/rag-content";
import { PLANS_PRICING_FILENAME } from "@/lib/plans-rag-doc";

export type RagFileMeta = {
  filename: string;
  title: string;
  category: string;
  charCount: number;
  updatedAt: string | null;
  autoGenerated: boolean;
  autoGeneratedNote?: string;
};

const AUTO_GENERATED: Record<string, string> = {
  [PLANS_PRICING_FILENAME]:
    "Legacy CRM-generated doc (internal). Public support AI uses plansrag.md instead.",
  "Olready_Sales_Toolkit.md":
    "Regenerated from the Master Knowledge file when you sync knowledge. Edit the Master file instead.",
};

const FILE_TITLES = new Map<string, { title: string; category: string }>([
  ...SUPPORT_POLICY_DOCS.map((d) => [d.file, { title: d.title, category: d.category }] as const),
  ...SALES_AI_DOCS.map((d) => [d.file, { title: d.title, category: "sales" }] as const),
]);

export const ALLOWED_RAG_FILENAMES = [...FILE_TITLES.keys()];

export function assertAllowedRagFilename(filename: string): string {
  const base = path.basename(filename);
  if (!ALLOWED_RAG_FILENAMES.includes(base)) {
    throw new Error("File not allowed");
  }
  return base;
}

export function listRagFiles(): RagFileMeta[] {
  return ALLOWED_RAG_FILENAMES.map((filename) => {
    const filePath = path.join(RAG_DIR, filename);
    const meta = FILE_TITLES.get(filename)!;
    const exists = fs.existsSync(filePath);
    const stat = exists ? fs.statSync(filePath) : null;

    return {
      filename,
      title: meta.title,
      category: meta.category,
      charCount: exists ? fs.readFileSync(filePath, "utf8").length : 0,
      updatedAt: stat ? stat.mtime.toISOString() : null,
      autoGenerated: filename in AUTO_GENERATED,
      autoGeneratedNote: AUTO_GENERATED[filename],
    };
  });
}

export function getRagFileForEdit(filename: string): {
  filename: string;
  content: string;
  autoGenerated: boolean;
  autoGeneratedNote?: string;
} {
  const safe = assertAllowedRagFilename(filename);
  const content = fs.existsSync(path.join(RAG_DIR, safe))
    ? readRagFile(safe)
    : "";

  return {
    filename: safe,
    content,
    autoGenerated: safe in AUTO_GENERATED,
    autoGeneratedNote: AUTO_GENERATED[safe],
  };
}

export function saveRagFile(filename: string, content: string): void {
  const safe = assertAllowedRagFilename(filename);
  if (safe === PLANS_PRICING_DOC.file) {
    throw new Error(
      "Olready_Plans_Pricing.md is CRM-generated. Edit plansrag.md for public support pricing instead.",
    );
  }

  const normalized = normalizeRagContent(content.trim());
  fs.mkdirSync(RAG_DIR, { recursive: true });
  fs.writeFileSync(path.join(RAG_DIR, safe), `${normalized}\n`, "utf8");
}
