"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { useToast } from "@/components/ui/Toast";
import type { AiDomain } from "@/lib/ai-domains";

type FileStatus = {
  filename: string;
  onDisk: boolean;
  diskChars: number;
  inSalesTable: boolean;
  inPolicyTable: boolean;
  dbCharCount: number;
  dbSynced: boolean;
  dbUpdatedAt: string | null;
};

type DomainOverview = {
  id: AiDomain;
  label: string;
  audience: string;
  description: string;
  usedBy: string;
  guardrails: string[];
  systemPrompt: string;
  temperature: number;
  maxTokens: number;
  customized: boolean;
  overrideUpdatedAt: string | null;
  files: FileStatus[];
  allFilesSynced: boolean;
};

type Overview = {
  model: string;
  hasOpenAiKey: boolean;
  ragDir: string;
  seedCommand: string;
  domains: DomainOverview[];
};

type RagFileMeta = {
  filename: string;
  title: string;
  category: string;
  charCount: number;
  updatedAt: string | null;
  autoGenerated: boolean;
  autoGeneratedNote?: string;
};

type HubPage = "assistants" | "knowledge";

const DOMAIN_TABS: { id: AiDomain; label: string }[] = [
  { id: "sales", label: "Sales" },
  { id: "support", label: "Public Support" },
  { id: "grievance", label: "Grievance" },
  { id: "rm", label: "RM" },
];

export function AdminAiHubClient() {
  const { toast } = useToast();
  const [hubPage, setHubPage] = useState<HubPage>("assistants");
  const [tab, setTab] = useState<AiDomain>("sales");
  const [overview, setOverview] = useState<Overview | null>(null);
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editPrompt, setEditPrompt] = useState("");
  const [editGuardrails, setEditGuardrails] = useState("");

  const [ragFiles, setRagFiles] = useState<RagFileMeta[]>([]);
  const [ragLoading, setRagLoading] = useState(false);
  const [selectedRag, setSelectedRag] = useState<string | null>(null);
  const [ragContent, setRagContent] = useState("");
  const [ragReadOnly, setRagReadOnly] = useState(false);
  const [ragNote, setRagNote] = useState<string | null>(null);
  const [ragSaving, setRagSaving] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    void fetch("/api/admin/ai/overview")
      .then((r) => r.json())
      .then((j) => setOverview(j.data ?? null))
      .finally(() => setLoading(false));
  }, []);

  const loadRagList = useCallback(() => {
    setRagLoading(true);
    void fetch("/api/admin/ai/rag")
      .then((r) => r.json())
      .then((j) => setRagFiles(j.data?.files ?? []))
      .finally(() => setRagLoading(false));
  }, []);

  const loadRagFile = useCallback((filename: string) => {
    setRagLoading(true);
    setSelectedRag(filename);
    void fetch(`/api/admin/ai/rag/${encodeURIComponent(filename)}`)
      .then((r) => r.json())
      .then((j) => {
        if (j.data) {
          setRagContent(j.data.content ?? "");
          setRagReadOnly(Boolean(j.data.autoGenerated));
          setRagNote(j.data.autoGeneratedNote ?? null);
        }
      })
      .finally(() => setRagLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    if (hubPage === "knowledge") {
      loadRagList();
    }
  }, [hubPage, loadRagList]);

  const domain = overview?.domains.find((d) => d.id === tab);

  useEffect(() => {
    if (!domain) return;
    setEditPrompt(domain.systemPrompt);
    setEditGuardrails(domain.guardrails.join("\n"));
  }, [domain?.id, domain?.systemPrompt, domain?.guardrails]);

  const sync = async () => {
    setSyncing(true);
    const res = await fetch("/api/admin/ai/overview", { method: "POST" });
    const json = await res.json();
    setSyncing(false);
    if (!res.ok) {
      toast(json.error ?? "Sync failed", "error");
      return;
    }
    toast("Knowledge synced from docs/RAG");
    load();
    if (hubPage === "knowledge") loadRagList();
  };

  const saveDomain = async () => {
    if (!domain) return;
    setSaving(true);
    const guardrails = editGuardrails
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);

    const res = await fetch(`/api/admin/ai/domains/${domain.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ systemPrompt: editPrompt, guardrails }),
    });
    const json = await res.json();
    setSaving(false);

    if (!res.ok) {
      toast(json.error ?? "Save failed", "error");
      return;
    }

    toast(`${domain.label} AI settings saved`);
    load();
  };

  const resetDomain = async () => {
    if (!domain) return;
    if (!confirm(`Reset ${domain.label} to code defaults? Custom prompt/guardrails will be removed.`)) {
      return;
    }

    setSaving(true);
    const res = await fetch(`/api/admin/ai/domains/${domain.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ reset: true }),
    });
    const json = await res.json();
    setSaving(false);

    if (!res.ok) {
      toast(json.error ?? "Reset failed", "error");
      return;
    }

    toast(`${domain.label} reset to defaults`);
    load();
  };

  const saveRagFile = async () => {
    if (!selectedRag || ragReadOnly) return;
    setRagSaving(true);
    const res = await fetch(`/api/admin/ai/rag/${encodeURIComponent(selectedRag)}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content: ragContent }),
    });
    const json = await res.json();
    setRagSaving(false);

    if (!res.ok) {
      toast(json.error ?? "Save failed", "error");
      return;
    }

    toast("Knowledge file saved and synced to database");
    loadRagList();
    load();
  };

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-brand">AI configuration</h1>
          <p className="mt-1 max-w-2xl text-sm text-slate-muted">
            Manage assistant prompts and the knowledge files in{" "}
            <code className="rounded bg-slate-100 px-1">docs/RAG</code>. Plan list prices live in{" "}
            <Link href="/admin/config" className="text-brand underline">
              Config → Plan tiers
            </Link>
            .
          </p>
        </div>
        <Button onClick={sync} disabled={syncing}>
          {syncing ? "Syncing…" : "Sync knowledge to DB"}
        </Button>
      </div>

      {overview && (
        <Card className="flex flex-wrap gap-4 p-4 text-sm">
          <div>
            <span className="text-slate-muted">Model</span>
            <p className="font-medium">{overview.model}</p>
          </div>
          <div>
            <span className="text-slate-muted">OpenAI key</span>
            <p className={overview.hasOpenAiKey ? "font-medium text-green-700" : "font-medium text-amber-700"}>
              {overview.hasOpenAiKey ? "Configured" : "Missing — fallback mode only"}
            </p>
          </div>
          <div>
            <span className="text-slate-muted">Knowledge folder</span>
            <p className="font-mono text-xs">{overview.ragDir}</p>
          </div>
        </Card>
      )}

      <div className="flex flex-wrap gap-2 border-b border-slate-100 pb-2">
        <button
          type="button"
          onClick={() => setHubPage("assistants")}
          className={`rounded-md px-3 py-1.5 text-sm font-medium ${
            hubPage === "assistants" ? "bg-brand text-white" : "text-slate-muted hover:bg-slate-100"
          }`}
        >
          Assistants
        </button>
        <button
          type="button"
          onClick={() => setHubPage("knowledge")}
          className={`rounded-md px-3 py-1.5 text-sm font-medium ${
            hubPage === "knowledge" ? "bg-brand text-white" : "text-slate-muted hover:bg-slate-100"
          }`}
        >
          Knowledge docs (RAG)
        </button>
      </div>

      {hubPage === "knowledge" && (
        <div className="grid gap-4 lg:grid-cols-[240px_1fr]">
          <Card className="p-3">
            <h2 className="mb-2 text-sm font-semibold">docs/RAG</h2>
            {ragLoading && !ragFiles.length && (
              <p className="text-xs text-slate-muted">Loading…</p>
            )}
            <ul className="space-y-1">
              {ragFiles.map((f) => (
                <li key={f.filename}>
                  <button
                    type="button"
                    onClick={() => loadRagFile(f.filename)}
                    className={`w-full rounded-md px-2 py-1.5 text-left text-xs ${
                      selectedRag === f.filename
                        ? "bg-brand/10 font-medium text-brand"
                        : "text-slate-700 hover:bg-slate-50"
                    }`}
                  >
                    <span className="block truncate">{f.title}</span>
                    <span className="text-[10px] text-slate-muted">
                      {Math.round(f.charCount / 1024)}k
                      {f.autoGenerated ? " · auto" : ""}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          </Card>

          <Card className="flex min-h-[420px] flex-col p-4">
            {!selectedRag ? (
              <p className="text-sm text-slate-muted">Select a knowledge file to view or edit.</p>
            ) : (
              <>
                <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <h3 className="font-mono text-sm">{selectedRag}</h3>
                    {ragNote && (
                      <p className="mt-1 text-xs text-amber-700">{ragNote}</p>
                    )}
                  </div>
                  {!ragReadOnly && (
                    <Button size="sm" onClick={() => void saveRagFile()} disabled={ragSaving}>
                      {ragSaving ? "Saving…" : "Save & sync to DB"}
                    </Button>
                  )}
                </div>
                <textarea
                  value={ragContent}
                  onChange={(e) => setRagContent(e.target.value)}
                  readOnly={ragReadOnly}
                  className={`min-h-[360px] flex-1 rounded-lg border px-3 py-2 font-mono text-xs leading-relaxed ${
                    ragReadOnly
                      ? "cursor-not-allowed border-slate-100 bg-slate-50 text-slate-600"
                      : "border-slate-200"
                  }`}
                />
              </>
            )}
          </Card>
        </div>
      )}

      {hubPage === "assistants" && (
        <>
          <div className="flex flex-wrap gap-2">
            {DOMAIN_TABS.map(({ id, label }) => {
              const d = overview?.domains.find((x) => x.id === id);
              return (
                <button
                  key={id}
                  type="button"
                  onClick={() => setTab(id)}
                  className={`rounded-md px-3 py-1.5 text-sm ${
                    tab === id ? "bg-slate-800 text-white" : "text-slate-muted hover:bg-slate-100"
                  }`}
                >
                  {label}
                  {d?.customized && <span className="ml-1 text-xs opacity-80">●</span>}
                  {d && !d.allFilesSynced && (
                    <span className="ml-1.5 text-amber-400" title="Some files not synced">
                      ○
                    </span>
                  )}
                </button>
              );
            })}
          </div>

          {loading && <p className="text-sm text-slate-muted">Loading…</p>}

          {domain && (
            <div className="space-y-4">
              <Card className="space-y-2 p-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h2 className="text-lg font-semibold">{domain.label}</h2>
                  {domain.customized && (
                    <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-800">
                      Customized
                      {domain.overrideUpdatedAt
                        ? ` · ${new Date(domain.overrideUpdatedAt).toLocaleDateString()}`
                        : ""}
                    </span>
                  )}
                </div>
                <p className="text-sm text-slate-muted">{domain.description}</p>
                <p className="text-xs text-slate-muted">
                  <strong>Audience:</strong> {domain.audience} · <strong>Used by:</strong> {domain.usedBy}
                </p>
                <p className="text-xs text-slate-muted">
                  Temperature {domain.temperature} · max {domain.maxTokens} tokens
                </p>
              </Card>

              <Card className="p-4">
                <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
                  <h3 className="font-semibold">Knowledge files</h3>
                  <button
                    type="button"
                    className="text-xs text-brand underline"
                    onClick={() => {
                      setHubPage("knowledge");
                      if (domain.files[0]) loadRagFile(domain.files[0].filename);
                    }}
                  >
                    Open in Knowledge docs →
                  </button>
                </div>
                <ul className="divide-y divide-slate-100 text-sm">
                  {domain.files.map((f) => (
                    <li key={f.filename} className="flex flex-wrap items-center justify-between gap-2 py-2">
                      <button
                        type="button"
                        className="font-mono text-xs text-brand underline"
                        onClick={() => {
                          setHubPage("knowledge");
                          loadRagFile(f.filename);
                        }}
                      >
                        {f.filename}
                      </button>
                      <span className="flex gap-3 text-xs text-slate-muted">
                        {f.onDisk ? `disk ${Math.round(f.diskChars / 1024)}k` : "missing on disk"}
                        {f.dbSynced ? (
                          <span className="text-green-700">DB synced ({Math.round(f.dbCharCount / 1024)}k)</span>
                        ) : (
                          <span className="text-amber-700">not in DB</span>
                        )}
                      </span>
                    </li>
                  ))}
                </ul>
              </Card>

              <Card className="space-y-3 p-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h3 className="font-semibold">Guardrails</h3>
                  <div className="flex gap-2">
                    <Button size="sm" variant="secondary" onClick={() => void resetDomain()} disabled={saving}>
                      Reset to defaults
                    </Button>
                    <Button size="sm" onClick={() => void saveDomain()} disabled={saving}>
                      {saving ? "Saving…" : "Save changes"}
                    </Button>
                  </div>
                </div>
                <p className="text-xs text-slate-muted">One rule per line.</p>
                <textarea
                  value={editGuardrails}
                  onChange={(e) => setEditGuardrails(e.target.value)}
                  rows={8}
                  className="w-full rounded-lg border border-slate-200 px-3 py-2 font-mono text-xs leading-relaxed"
                />
              </Card>

              <Card className="space-y-3 p-4">
                <h3 className="font-semibold">System prompt</h3>
                <textarea
                  value={editPrompt}
                  onChange={(e) => setEditPrompt(e.target.value)}
                  rows={16}
                  className="w-full rounded-lg border border-slate-200 px-3 py-2 font-mono text-xs leading-relaxed"
                />
                <p className="text-xs text-slate-muted">
                  Saved overrides apply immediately. Code defaults in{" "}
                  <code className="rounded bg-slate-100 px-1">lib/ai-domains.ts</code>.
                </p>
              </Card>
            </div>
          )}
        </>
      )}
    </div>
  );
}
